### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by eabdalmufid** [homer0/cjs2esm#24]
Before
![Screenshot_2024-02-21-17-16-06-392_com rhmsoft edit pro-edit](https://github.com/homer0/cjs2esm/assets/110360966/b85e8783-667e-4ae2-b123-b05ed886a4e7)

After
![Screenshot_2024-02-21-17-15-33-354_com rhmsoft edit pro-edit](https://github.com/homer0/cjs2esm/assets/110360966/cd33f098-b789-43a3-839d-478c648dc29a)

**Comment by homer0** [comment]
Hi @eabdalmufid!

That looks related to the fact that you are using dynamic paths on your `require`s, so [`5to6`](https://github.com/5to6/5to6-codemod) can't convert them to static imports. When using ESM and dynamic paths, you have to use the `import` function:

```js
const { color } = await import(__path + '...');
```

> That works on both ESM and CJS.

`require`'s with dynamic paths can't be converted, because this doesn't exist in ESM:

```js
import { color } from __path + '...';
```
